---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
    service: kafka
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - name: broker
      port: 9092
  selector:
    service: kafka
