---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  labels:
    name: kafka-3
    service: kafka
    broker_id: "3"
spec:
  # clusterIP: 10.200.10.33
  # type: ClusterIP
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-3
    broker_id: "3"
